name: optimizely_plugin
description: Flutter plugin for Optimizely SDK
version: 0.1.3
homepage: https://www.policygenius.com/
repository: https://github.com/policygenius/optimizely-plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.policygenius.optimizely_plugin
        pluginClass: OptimizelyPlugin
      ios:
        pluginClass: OptimizelyPlugin
